name: sample-workflow
on:
  push:
    branches: [master]
    
jobs:
  job1:
    run-on: ubuntu-latest
    steps:
    - name: checks-out your repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v2
    - name: use echo command
      uses: echo "sample-workflow"
